### ISSUE TITLE
Write Up Summaries of Open Days

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#10]

**Comment by TheLostLambda** [comment]
For @KOXLEY2 and @mariojgarciad , what still needs to be done here? And what sort of deadline seems reasonable? I was under the impression that quite a bit of it was already done?

**Comment by KOXLEY2** [comment]
https://docs.google.com/document/d/1uFF1yksCiBRpyRQs9601_70Nw_okAER5QpcvL2ZUUv4/edit 

Still  a few edits

**Comment by alwinthomas409** [comment]
Just made a change @KOXLEY2

**Comment by TheLostLambda** [comment]
Has this been wrapped up nicely now?

**Comment by alwinthomas409** [comment]
Yeah it's all done just left as uncomplete on guthub.
