### ISSUE TITLE
Preliminary Safety Form

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#16]
Best be done prior to lab work I guess- actual deadline is 5/6/24

**Comment by TheLostLambda** [comment]
Here is some more information from the iGEM website!
https://competition.igem.org/deliverables/safety-forms

**Comment by TheLostLambda** [comment]
I think @Yvaei might spearhead the organising of this, since she should have some time now, but @KOXLEY2 , @mariojgarciad , @ikesadbot and I (@TheLostLambda ) should all be around to answer questions or fill in missing sections with spare moments!

**Comment by Yvaei** [comment]
Hi h=guys just working on the form and wanted to cross-check, in which lab we will be working at? Also do you have any photos of it?

**Comment by mariojgarciad** [comment]
Very sorry. Didn't know you had started. I'm working on it here if you wanna add to it? It's nearly done. Sorry about the miscommunication https://docs.google.com/document/d/1ykNS6YsLbC9PSGEn_Le3o_MvdVKcZuYngniviL-59U8/edit?pli=1

**Comment by Yvaei** [comment]
AH no worriea then! Let me know if you need any help :)

**Comment by mariojgarciad** [comment]
Thank u. Please, give it a check if u can. It's good to cross-check it with other people
