### ISSUE TITLE
Create an iGEM Account & Join Team

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#31]
After creating an account here: [https://accounts.igem.org/](https://accounts.igem.org/), be sure to request to join the team here: [https://teams.igem.org/5172](https://teams.igem.org/5172)!

**Comment by Gracemarsden04** [comment]
Just done this now!

**Comment by funnirudh** [comment]
Just created the account and applied for the team.

**Comment by alwinthomas409** [comment]
I am part of the team, joined a while ago, just need to submit it as
compete I think.
