### ISSUE TITLE
Conservation X prize

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#33]
Great to have down here! Could you (@KOXLEY2) link the draft application Google doc so that I could give it a read over?

P.S. Feel free to do the "Convert to Issue" thing, and select the `.github` repository when you're adding things in the future!

**Comment by KOXLEY2** [comment]
https://docs.google.com/document/d/1ubOEMMThvv5P87z18_n9GIIA5T-q5sZPuJJFunWitWw/edit

oO Github confuses me

**Comment by TheLostLambda** [comment]
@mariojgarciad and @TheLostLambda should give this a read on Friday!
