### ISSUE TITLE
Write the introduction for the project proposal

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#41]
You should be able to recycle a lot from the literature review! We want to hit all of the criteria for the Project Description: https://competition.igem.org/deliverables/project-description **except for** the "what we hope to accomplish", since that will be covered by the experimental plan portion of the proposal!

Let me know @alwinthomas409 if this is self-contained enough!

**Comment by alwinthomas409** [comment]
Can you send me a link to previous project templates that i can base this one off?
