### ISSUE TITLE
Leave comments on the literature review

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#42]
I'm not sure if you've already read through things, but the more eyes on the draft and the more comments people have to look at and refine things, the better!

If you have the time in the next couple of days, great! If not, just let me know!

https://docs.google.com/document/d/14othmXs9GpM7u-JtIA3isqFbXPbgbWOBCQICikdZAaA/edit#heading=h.fzglws12qf06

**Comment by funnirudh** [comment]
I did give it a brief read earlier to get an idea of the project. I will read it once more and provide my comments within the document soon. Will update here accordingly.
