### ISSUE TITLE
Add references for Alwin's section

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#51]

**Comment by Gracemarsden04** [comment]
@TheLostLambda I've just done this and tried to mark it as complete but its not letting me, im not sure if I don't have permissions or something like that?

**Comment by TheLostLambda** [comment]
@Gracemarsden04 Whoops! You should be able to? Though you might have to do it from the projects page / mainboard? By marking it "Done"?


![Image](https://github.com/Sheffield-iGEM/.github/assets/6251883/356474fb-38a1-4e54-9bb8-aa19a35c37e3)

Let me know if that works for you!

**Comment by TheLostLambda** [comment]
(I'll leave this open so that you can test it works for you!)

**Comment by Gracemarsden04** [comment]
It's let me now! Thank you!
