### ISSUE TITLE
Email Jacob, Mary, and Archie about joining

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#53]
Need to make sure they have the time / are still free over the summer and want to do iGEM, and for Archie, it might be good to get some basic CV / interview style information!

**Comment by mariojgarciad** [comment]
I've emailed Archie and Jacob. and was about to email Mary but thought it sane to check whether we are prepared that all 3 of them could say yes and we're ok with having 3 more team members? (Just sanity checking. I loved Jacob and Mary and Archie is Alwin's friend so pretty sure I'll love him too:))

**Comment by TheLostLambda** [comment]
Sorry @mariojgarciad , I read this before, but missed the question you asked 😅 

I see you've emailed Mary now and I think that's alright!
