### ISSUE TITLE
Discuss the team Laval Video submission

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#58]
They said a month deadline on the 13th of May and we was like HUH? exam season and so far they is like ...................

**Comment by TheLostLambda** [comment]
Hahaha — could be neat, but I'm not sure if more work is particularly what we want or need at the moment?

**Comment by KOXLEY2** [comment]
Let's go for something simple and get this out in the next week or two!

**Comment by TheLostLambda** [comment]
We're doing one alongside the project description, though that's not a particularly set deadline?
