### ISSUE TITLE
Reply to school email about summer days

### ISSUE THREAD

**Issue by KOXLEY2** [Sheffield-iGE/.github#60]
Rebecca Humphreys <Rebecca.Humphreys@sheffieldparkacademy.org>
We are interested, what age group is this aimed at?

Mrs Humphreys Head of Science

**Comment by KOXLEY2** [comment]
Waiting on a reply from the one person who emailed us back?

**Comment by KOXLEY2** [comment]
Mary might reach out too!

**Comment by KOXLEY2** [comment]
@co1een is happy to do a bit of emailing too after knowing who we have already emailed!

**Comment by KOXLEY2** [comment]
Potentially Silverdale!

**Comment by KOXLEY2** [comment]
Also to Mary!

**Comment by TheLostLambda** [comment]
I think it's time we replace this task with some more specific ones! Does anyone who is up to speed on the school-outreach want to create some new tasks and close this one?
