### ISSUE TITLE
Contact someone from the Baker lab about giving a seminar

### ISSUE THREAD

**Issue by KOXLEY2** [Sheffield-iGE/.github#65]

**Comment by KOXLEY2** [comment]
Or more specifically: Justas Dauparas

**Comment by JacobLenton** [comment]
Hi, I just wanted to check if we also need to send an email to companies about how they would use the improved enzyme? If so, is there a list of contacts we currently have? Thanks :)

**Comment by KOXLEY2** [comment]
Should ask Felix about getting in touch with Baker lab members

**Comment by alwinthomas409** [comment]
@TheLostLambda did you send the email regarding Justas?

**Comment by TheLostLambda** [comment]
@alwinthomas409 I did! I copied the iGEM email in too, but no news so far...

**Comment by TheLostLambda** [comment]
I think we'll need to chase Felix for some different contacts he might have...

**Comment by Gracemarsden04** [comment]
Sounds like Felix is our man?
