### ISSUE TITLE
Ask wastewater treatment people about how we might pull phosphate from wastewater?

### ISSUE THREAD

**Issue by KOXLEY2** [Sheffield-iGE/.github#73]
Maybe try to set up a meeting?

Also ask if she has more contacts outside of the university who we could chat to?

Speakers for people running plants? What practicalities?

**Comment by Yvaei** [comment]
Some companies that I found: 

https://enzymesupplies.com - they assist in bringing new enzymes to the market and specialise within agriculture. 

Lucerne biotech UK Ltd, link doesn't work - LinkedIn? - specialised in bioaugmentation, bioremediation. Involved in water treatments. 

Bluewater Bio https://bluewaterbio.com - have R&D team and seem big on innovation part and involved in multiple different water treatments applications.

**Comment by Yvaei** [comment]
Other cool companies just not in UK. 

Denmark https://www.novozymes.com/en - they also use and apply enzymes for agriculture purposes.

https://antozymebiotech.com - use of enzymes for water treatments. 

https://www.zymatic.com/industry - use of enzymes for water treatments.

**Comment by Gracemarsden04** [comment]
Need to catch up with @Yvaei !
