### ISSUE TITLE
Who needs a Visa + start the process!

### ISSUE THREAD

**Issue by KOXLEY2** [Sheffield-iGE/.github#79]
Just double check!

**Comment by Gracemarsden04** [comment]
Go here: https://competition.igem.org/participation/visa-invitation-letter

If you need the PI login, ask @ikesadbot @TheLostLambda @KOXLEY2 @mariojgarciad ?

**Comment by TheLostLambda** [comment]
Have both @co1een and @funnirudh started this / have this under control?
