### ISSUE TITLE
Start some practice M&M writing

### ISSUE THREAD

**Issue by KOXLEY2** [Sheffield-iGE/.github#80]
Isaac has a good example! Get everyone to do a bit!

**Comment by TheLostLambda** [comment]
@ikesadbot I know ur on holiday, sexy boi, but can you send your full-mark materials and methods if you'd not already (so we can put it in the "training materials" folder on the drive?

**Comment by Gracemarsden04** [comment]
Things started --- just need a sanity-check / read over! From @TheLostLambda  and @ikesadbot
