### ISSUE TITLE
Make a characterisation checklist for PafA

### ISSUE THREAD

**Issue by TheLostLambda** [Sheffield-iGE/.github#81]
For people who have some time to think about the biology / best basic part prize, we should look at the judging handbook, look at the two examples they give of well characterized parts, then make a checklist of the things we can do for PafA!

Then as we go through in the lab, we can check off those experiments and make some nice figures to add!

We should know all of the figures that we want on the final page before starting all of the work in the lab!

For @KOXLEY2 , please assign some others to this that you think have the time!

**Comment by Gracemarsden04** [comment]
https://docs.google.com/document/d/1cL0HMiTMnJ9fH_-zp3qVDyikylf6Slr9xiJNwKuuox8/edit
