### ISSUE TITLE
Choosing the PafA variants from the results

### ISSUE THREAD

**Issue by Gheist404** [Sheffield-iGE/.github#96]
All the PafA variants have been made and an email has been sent to Felix which has the iGEM email cc. This is a link to the data in the google drive:
https://drive.google.com/drive/folders/1DLaMJt_S8sLTULc9NShQn_LoRNUos-hW?usp=drive_link 
Can we get these chosen by the 19th of July in order to get the gBlocks ordered ASAP

**Comment by TheLostLambda** [comment]
If it's alright, I might take some of the weekend to poke around! Is ordering on Monday morning at the latest still acceptable? Gives everyone a bit more time to take a look!

**Comment by TheLostLambda** [comment]
And we want to go down from 21 variants to 12, right? So eliminating 9 of them?
